project:
  type: website
  output-dir: _site
  resources:
    - static/uploads/resume.pdf
  render:
    - index.qmd
    - pages/*.qmd

website:
  title: "Minhyun Lee"
  site-url: "https://minhyunlee.github.io"
  search: false
  navbar:
    background: "#ffffff"
    foreground: "#111111"
    pinned: true
    left:
      - href: index.qmd#about
        text: About
      - href: index.qmd#news
        text: News
      - href: index.qmd#publications
        text: Publications
      - href: index.qmd#education
        text: Education
      - href: index.qmd#experience
        text: Experience
      - href: index.qmd#academic-services
        text: Academic Services
    right:
      - text: CV
        href: "static/uploads/resume.pdf"
      - text: Scholar
        href: "https://scholar.google.com/citations?user=2hUlCnQAAAAJ&hl=ko"
      - text: GitHub
        href: "https://github.com/gaviotas"
  page-footer:
    border: false
    left: "Minhyun Lee"
    right: ""

format:
  html:
    theme:
      light: [sandstone, styles.scss]
    toc: false
    anchor-sections: false
    smooth-scroll: true
    link-external-newwindow: true

execute:
  freeze: auto
