[build]
  command = "quarto render"
  publish = "_site"

[build.environment]
  QUARTO_VERSION = "1.7.32"

[context.deploy-preview]
  command = "quarto render"

[context.branch-deploy]
  command = "quarto render"
